# Generated by Django 2.1.5 on 2019-01-20 22:23

from django.db import migrations, models
import shop_temp.models


class Migration(migrations.Migration):

    dependencies = [
        ('shop_temp', '0002_product'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='slug',
            field=models.SlugField(blank=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='image',
            field=models.ImageField(upload_to=shop_temp.models.image_folder),
        ),
    ]
