# Generated by Django 2.1.5 on 2019-01-20 23:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop_temp', '0003_auto_20190120_2223'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='avaliable',
            new_name='available',
        ),
    ]
